2021-09-20 23:05:10,289 INFO    Thread-3  :551085 [wandb_setup.py:_flush():69] setting env: {'project': 'simple-classification-sweep', 'entity': 'sang-hyun', 'root_dir': '/tf/CI/MyTorchTemplate', 'sweep_id': 'ucvr3t6b', 'run_id': 'nn7o3ivv', 'sweep_param_path': '/tf/CI/MyTorchTemplate/wandb/sweep-ucvr3t6b/config-nn7o3ivv.yaml'}
2021-09-20 23:05:10,289 INFO    Thread-3  :551085 [wandb_setup.py:_flush():69] setting login settings: {}
2021-09-20 23:05:10,290 INFO    Thread-3  :551085 [wandb_init.py:_log_setup():342] Logging user logs to /tf/CI/MyTorchTemplate/wandb/run-20210920_230510-nn7o3ivv/logs/debug.log
2021-09-20 23:05:10,290 INFO    Thread-3  :551085 [wandb_init.py:_log_setup():343] Logging internal logs to /tf/CI/MyTorchTemplate/wandb/run-20210920_230510-nn7o3ivv/logs/debug-internal.log
2021-09-20 23:05:10,290 INFO    Thread-3  :551085 [wandb_init.py:init():375] calling init triggers
2021-09-20 23:05:10,291 INFO    Thread-3  :551085 [wandb_init.py:init():382] wandb.init called with sweep_config: {'ARCHITECTURE': 'single-layer-perceptron', 'DATASET': 'MNIST-handwrite', 'DATA_PATH': '../dataset/', 'NOW': '2021-09-20T23:05:08', 'SAVEFIG_NAME': 'result.png', 'batchsize': 16, 'epochs': 10, 'learning_rate': 0.06480879826612677}
config: {}
2021-09-20 23:05:10,291 INFO    Thread-3  :551085 [wandb_init.py:init():424] starting backend
2021-09-20 23:05:10,291 INFO    Thread-3  :551085 [backend.py:_multiprocessing_setup():72] multiprocessing start_methods=fork,spawn,forkserver, using: spawn
2021-09-20 23:05:10,298 INFO    Thread-3  :551085 [backend.py:ensure_launched():135] starting backend process...
2021-09-20 23:05:10,302 INFO    Thread-3  :551085 [backend.py:ensure_launched():140] started backend process with pid: 551141
2021-09-20 23:05:10,302 INFO    Thread-3  :551085 [wandb_init.py:init():429] backend started and connected
2021-09-20 23:05:10,304 INFO    Thread-3  :551085 [wandb_run.py:_config_callback():843] config_cb None None {'ARCHITECTURE': 'single-layer-perceptron', 'DATASET': 'MNIST-handwrite', 'DATA_PATH': '../dataset/', 'NOW': '2021-09-20T23:05:08', 'SAVEFIG_NAME': 'result.png', 'batchsize': 16, 'epochs': 10, 'learning_rate': 0.06480879826612677}
2021-09-20 23:05:10,304 INFO    Thread-3  :551085 [wandb_init.py:init():477] updated telemetry
2021-09-20 23:05:10,304 INFO    Thread-3  :551085 [wandb_init.py:init():500] communicating current version
2021-09-20 23:05:10,778 INFO    Thread-3  :551085 [wandb_init.py:init():505] got version response upgrade_message: "wandb version 0.12.2 is available!  To upgrade, please run:\n $ pip install wandb --upgrade"

2021-09-20 23:05:10,778 INFO    Thread-3  :551085 [wandb_init.py:init():513] communicating run to backend with 30 second timeout
2021-09-20 23:05:11,394 INFO    Thread-3  :551085 [wandb_init.py:init():540] starting run threads in backend
2021-09-20 23:05:12,263 INFO    Thread-3  :551085 [wandb_run.py:_console_start():1601] atexit reg
2021-09-20 23:05:12,264 INFO    Thread-3  :551085 [wandb_run.py:_redirect():1475] redirect: SettingsConsole.REDIRECT
2021-09-20 23:05:12,264 INFO    Thread-3  :551085 [wandb_run.py:_redirect():1480] Redirecting console.
2021-09-20 23:05:12,265 ERROR   Thread-3  :551085 [wandb_run.py:_redirect():1539] Failed to redirect.
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/wandb/sdk/wandb_run.py", line 1532, in _redirect
    out_redir.install()
  File "/usr/local/lib/python3.6/dist-packages/wandb/sdk/lib/redirect.py", line 709, in install
    _WSCH.add_fd(self._pipe_read_fd)
  File "/usr/local/lib/python3.6/dist-packages/wandb/sdk/lib/redirect.py", line 659, in add_fd
    self._register()
  File "/usr/local/lib/python3.6/dist-packages/wandb/sdk/lib/redirect.py", line 644, in _register
    old_handler = signal.signal(signal.SIGWINCH, lambda *_: None)
  File "/usr/lib/python3.6/signal.py", line 47, in signal
    handler = _signal.signal(_enum_to_int(signalnum), _enum_to_int(handler))
ValueError: signal only works in main thread
2021-09-20 23:05:12,265 INFO    Thread-3  :551085 [wandb_init.py:init():565] run started, returning control to user process
2021-09-20 23:05:12,265 INFO    Thread-3  :551085 [wandb_config.py:__setitem__():141] config set name = sweep-2021-09-20T23:05:12 - <bound method Run._config_callback of <wandb.sdk.wandb_run.Run object at 0x7f81847a8a20>>
2021-09-20 23:05:12,265 INFO    Thread-3  :551085 [wandb_run.py:_config_callback():843] config_cb name sweep-2021-09-20T23:05:12 None
2021-09-20 23:05:12,306 INFO    Thread-3  :551085 [wandb_run.py:finish():1271] finishing run sang-hyun/simple-classification-sweep/nn7o3ivv
